version: 0.4.{build}
skip_tags: true
configuration: Release
platform: AnyCPU
clone_depth: 2
branches:
  only:
  - master
install:
- choco install gitlink -y
before_build:
- ps: .\SetVersion.ps1
- appveyor-retry dotnet restore -v Minimal
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
before_package:
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { GitLink .\ }
after_test: 
- ps: .\CreateCoverage.ps1
environment:
  COVERALLS_REPO_TOKEN:
    secure: 5WWUHMA6N4J56uA5Or7KTn56RYcGHDnTTIxqxGmWyoEpdhkasFIAfeOrFnCLxFPt
  confluence_test_username:
    secure: gdcMwbkCpbe2jH691vkZqw==
  confluence_test_password:
    secure: Ok03X5fvfNY2h61MHktUJw==
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
build_script:
- dotnet build Dapplo.Confluence -c %CONFIGURATION% --no-dependencies
- dotnet build Dapplo.Confluence.Tests -c %CONFIGURATION% --no-dependencies
after_build:
- dotnet pack Dapplo.Confluence -c %CONFIGURATION% --no-build -o artifacts
#- dotnet pack Dapplo.Confluence.PowerShell -c %CONFIGURATION% --no-build -o artifacts
#cache:
#- '%USERPROFILE%\.nuget\packages'
artifacts:
- path: artifacts\**\*.*
  name: NuGet package
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: xkDQ385+smLqdzhESsXBJvnUjK4FZ4Djjrqi9tFR29dwESIvPYOrQAqgri5Nf/fA
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/
